### ISSUE TITLE
Request to add product in Start Flutter.

### ISSUE THREAD

**Issue by maheshwari-1153** [JideGuru/FlutterFoodybite#3]
Hello,

I am Maheshwari from team [GeekyAnts](https://geekyants.com/). On behalf of [Start Flutter](https://startflutter.com/), we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website.

Looking forward to hear from you.

**Comment by JideGuru** [comment]
Hello, i would love to showcase my product on your website. Thank you for the consideration.

**Comment by maheshwari-1153** [comment]
Thanks, I will let you know once your product is added in the website.
